target 'Quizmaster' do

  pod 'Firebase/Core'
  pod 'Firebase/Database'

  pod 'react-native-video', :path => '../node_modules/react-native-video'

  pod 'RNSound', :path => '../node_modules/react-native-sound'

  pod 'BVLinearGradient', :path => '../node_modules/react-native-linear-gradient'

end